# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS_App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'flutter_lib', :path => '../flutter_lib'
  
  # Pods for iOS_App

  target 'iOS_AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOS_AppUITests' do
    # Pods for testing
  end

end
